[tools]
slsa-verifier = "latest"
cosign = "latest"
rust = "stable"
uv = "latest"
npm = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust", "python", "node", "java"]

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.npm]
package_manager = "bun"
